#Makefile for CPP program - Akash Gaikwad

#compiler
CC = g++

#Compiler flags for Warning and debugging
CFLAGS= -Wall -g  -std=c++11

#Target 
TARGET = p1

$(TARGET): $(TARGET)
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).cpp

clean:
	$(RM) $(TARGET)
